project:
  title: "2023 Everyday AI Hackathon"
  output-dir: ./docs/en

website:
  favicon: favicon.ico
  open-graph:
    title: "2023 Everyday AI Hackathon"
    description: "The Everyday AI Hackathon is where Hugging Face enthusiasts in Korea meet."
    image: assets/images/hackathon-960x540.png
  twitter-card:
    title: "2023 Everyday AI Hackathon"
    description: "The Everyday AI Hackathon is where Hugging Face enthusiasts in Korea meet."
    image: assets/images/hackathon-960x540.png
  google-analytics: "G-HMKJZ8LF1Y"
  page-navigation: true
  site-url: https://pseudo-lab.github.io/huggingface-hackathon23/
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon"
  body-header: |
    <button onclick="window.location = location.href.replace('/en/','/ko/');" class="btn btn-translate">
      <i class="bi bi-translate"></i> 한국어 버전
    </button>

  navbar:
    logo: assets/images/navbar-logo.png
    title: " "
    search: true
    left:
      - text: About
        file: index.qmd
      - icon: bookmark-star
        text: Submit your Project
        href: https://huggingface.co/organizations/pseudolab/share/UYPZnwyOTadGJDReehItrwtbWKSxHYmAku
        target: blank
      - icon: building-check
        text: Offline event
        href: https://event-us.kr/huggingfacekrew/event/72612
        target: blank
    tools:
      - icon: discord
        href: https://hf.co/join/discord
        target: blank

  sidebar:
    # logo: assets/images/poster.png
    pinned: true
    align: center

    style: floating
    contents:
      - index.qmd
      - section: Tutorials
        contents:
          - text: 01_Joining Discord
            contents: tutorials/*
            file: tutorials/discord.qmd
          - text: 02_Creating a Project
            file: tutorials/hf_hub.qmd
          - text: 03_Contributions and Submissions
            file: tutorials/pr_guide.qmd
      - href: presentations/index.qmd
        text: Presentations


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/static/pretendard.css" type="text/css"/>

mainfont: Pretendard

filters:
  - include-files.lua
  - quarto
