project: 
  type: website

website:
  page-navigation: true  
  title: "2023 Everyday AI Hackathon"
  site-url: https://pseudo-lab.github.io/huggingface-hackathon23/
  
  repo-url: https://github.com/Pseudo-Lab/huggingface-hackathon23
  repo-actions: [edit, issue]
  
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon" 
 
  sidebar:
    logo: https://github.com/Pseudo-Lab/huggingface_krew/assets/29195190/78f067c4-99e0-42bc-8d9f-06155c4ee9be
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://pseudo-lab.github.io/huggingface-hackathon23/
        text: "PseudoLab website"
      - icon: github
        href: https://github.com/Pseudo-Lab/huggingface-hackathon23
        text: "2023 Everyday AI Hackathon repo"
    
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Welcome"
        contents:
          - index.md
          - huggingface.md
          - team.md
      - section: "Logistics"
        contents:
          - logistics/index.md
          - logistics/schedule.md
          - logistics/prerequisites.md
          - logistics/github-workflows.md
      - section: "Tutorials"
        contents: 
          - tutorials/index.md
      - section: "Tutorial Templates"
        contents: 
          - tutorials-templates/index.md 
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - further-resources.md
      - section: "Pre-Hackathon-Clinic"
        contents:
          - clinic/index.md
          - clinic/huggingfacehub.md
          - clinic/notebooks.md
          - clinic/github.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
