project:
  title: "2023 일상에서의 AI 해커톤"
  output-dir: ./_site/ko

website:
  page-navigation: true
  site-url: https://pseudo-lab.github.io/huggingface-hackathon23
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon"
  body-header: |
    <button onclick="window.location = location.href.replace('/ko/','/en/');" class="btn btn-translate">
      <i class="bi bi-translate"></i> See in English
    </button>

  navbar:
    search: true
    left:
      - text: 소개
        file: index.qmd
      - text: 운영안내
        file: logistics/index.qmd
      - text: 튜토리얼
        file: tutorials/index.qmd
      - text: 제출하기
        file: submit.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com

  sidebar:
    - title: 운영 안내
      style: floating
      contents:
        - text: 주요 안내사항
          file: logistics/index.qmd
        - text: 팀 결성 방법
          file: logistics/how-to-form-teams.qmd
        # - text: 사전준비 사항
        #   file: logistics/prerequisites.qmd

    - title: 튜토리얼
      contents:
        - text: 개요
          file: tutorials/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
