project: 
  type: website

website:
  page-navigation: true  
  title: "2023 Everyday AI Hackathon"
  site-url: https://pseudo-lab.github.io/2023-EverydayAI-Hackathon
  
  repo-url: https://github.com/Pseudo-Lab/huggingface_krew/tree/23hackathon
  repo-actions: [edit, issue]
  
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon" 
 
  sidebar:
    logo: https://github.com/Pseudo-Lab/huggingface_krew/assets/29195190/78f067c4-99e0-42bc-8d9f-06155c4ee9be
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://pseudo-lab.github.io
        text: "PseudoLab website"
      - icon: github
        href: https://github.com/Pseudo-Lab/huggingface_krew/tree/23hackathon
        text: "2023 Everyday AI Hackathon repo"
    
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Welcome"
        contents:
          - index.md
          - huggingface.md
          - team.md
      - section: "Logistics"
        contents:
          - logistics/index.md
          - logistics/schedule.md
          - logistics/prerequisites.md
          - logistics/github-workflows.md
      - section: "Tutorials"
        contents: 
          - tutorials/index.md
          - tutorials/00_Setup.md  ## tutorial 0
          - tutorials/01_Data_Discovery_CMR.ipynb ## tutorial 1
          - tutorials/02_Data_Discovery_CMR-STAC_API.ipynb ## tutorial 2
          - tutorials/03_Xarray.ipynb ## tutorial 3
          - tutorials/04_NASA_Earthdata_Authentication.ipynb ## tutorial 4
          - tutorials/05_Data_Access_Direct_S3.ipynb ## tutorial 5
          - tutorials/06_S6_OPeNDAP_Access_Gridding.ipynb ## tutorial 6
          - tutorials/07_Harmony_Subsetting.ipynb ## tutorial 7
          - tutorials/08_On-Prem_Cloud.ipynb ## tutorial 8
          - tutorials/09_Zarr_Access.ipynb ## tutorial 9
      - section: "Tutorial Templates"
        contents: 
          - tutorials-templates/index.md 
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - further-resources.md
      - section: "Pre-Hackathon-Clinic"
        contents:
          - clinic/index.md
          - clinic/jupyterhub.md
          - clinic/notebooks.md
          - clinic/github.md
          - clinic/earthdata.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
