project:
  title: "2023 Everyday AI Hackathon"
  output-dir: ./_site/en

website:
  page-navigation: true
  site-url: https://pseudo-lab.github.io/huggingface-hackathon23/
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon"
  body-header: |
    <button onclick="window.location = location.href.replace('/en/','/ko/');" class="btn btn-translate">
      <i class="bi bi-translate"></i> 한국어 버전
    </button>

  navbar:
    search: true
    left:
      - text: About
        file: index.qmd
      - text: Logistics
        file: logistics/index.qmd
      - text: Tutorials
        file: tutorials/index.qmd
      - text: Submit
        file: submit.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com

  sidebar:
    - title: Logistics
      style: floating
      contents:
        - text: Main Guidelines
          file: logistics/index.qmd
        - text: How to Form a Team
          file: logistics/how-to-form-teams.qmd
        # - text: 사전준비 사항
        #   file: logistics/prerequisites.qmd

    - title: Tutorials
      contents:
        - text: Overview
          file: tutorials/index.qmd
      
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
