project:
  title: "2023 일상에서의 AI 해커톤"
  output-dir: ./_site/ko

website:
  favicon: favicon.ico
  open-graph:
    title: "2023 일상에서의 AI 해커톤"
    description: "일상에서의 AI 해커톤은 국내 Hugging Face 사용자들이 모인 교류의 장으로써 기획되었습니다."
    image: assets/images/hackathon-960x540.png
  twitter-card:
    title: "2023 일상에서의 AI 해커톤"
    description: "일상에서의 AI 해커톤은 국내 Hugging Face 사용자들이 모인 교류의 장으로써 기획되었습니다."
    image: assets/images/hackathon-960x540.png
  page-navigation: true
  site-url: https://pseudo-lab.github.io/huggingface-hackathon23
  page-footer: "Pseudo Lab (2023). 2023 Everyday AI Hackathon"
  body-header: |
    <button onclick="window.location = location.href.replace('/ko/','/en/');" class="btn btn-translate">
      <i class="bi bi-translate"></i> See in English
    </button>

  navbar:
    logo: assets/images/navbar-logo.png
    title: " "
    search: true
    left:
      - text: 소개
        file: index.qmd
      - icon: bookmark-star
        text: 데모 제출
        href: https://huggingface.co/pseudolab
        target: blank
      - icon: building-check
        text: 오프라인 참가
        href: https://event-us.kr/huggingfacekrew/event/72612
        target: blank
    tools:
      - icon: discord
        href: https://hf.co/join/discord
        target: blank

  sidebar:
    # logo: assets/images/poster.png
    pinned: true
    align: center

    style: floating
    contents:
      - index.qmd
      - section: 튜토리얼
        contents: tutorials/*

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
