The **Everyday AI Hackathon** is a collaborative open science learning experience aimed at fostering innovation and practical knowledge in AI. The goals are to:

- **Empower Participants:** Enable every participant to harness the power of AI to solve real-world problems and make a positive impact.
- **Foster Learning and Collaboration:** Create a supportive environment where participants can learn from each other, share knowledge, and collaborate to bring ideas to life.
- **Promote Practical Application of AI:** Encourage the development and implementation of AI solutions that are applicable and beneficial in everyday scenarios.
- **Strengthen Community Engagement:** Build a strong, inclusive, and diverse community that continues to collaborate and grow in the field of AI, contributing to open science and open data initiatives.

**Outcome**: Participants will prototype AI applications, developing practical AI solutions and contributing to the open community. This event is an opportunity for individuals of all levels to explore, learn, and prototype workflows, enhancing their skills and understanding of AI.

This is an opportunity for researchers, students, and professionals who might not yet have had the opportunity to work with Hugging Face technology to explore, learn, and prototype workflows, but more intermediate or advanced users interested in further exploring AI applications are also welcome.

## Application

### Information for applicants

The Everyday AI Hackathon is where participants will explore the intersection of AI, Hugging Face technology, and daily life through demonstration tutorials and hands-on “hacking” projects. To best benefit from the event, we recommend some familiarity or experience with:

- Hugging Face technology and tools; and
- Programming skills using Python. We plan to accept participants with diverse skill levels and backgrounds in programming. However, to best benefit from and contribute to the program, participants are expected to have some experience with Python programming.

No prior experience with Hugging Face technology is required, but we encourage both beginner and more experienced participants to apply.

### Application Form

In the application form, we encourage you to think about and provide an AI use case that you would like to prototype. During the hackathon, participants will get into teams of their choosing, around a common use case to “hack” - by which we mean collaboratively experiment working in with Hugging Face technology. The use cases provided in the application form will also help the organizers best prepare materials tailored to those use cases.

**Applications are now open! Please apply [here]()**

## What to expect

* During the Everyday AI Hackathon, the selected participants will have access to Cloud environments and will be guided on how to use the environment, import needed data recipes and resources, and will have the opportunity to explore and develop AI applications using example tutorials as building blocks.
* Participants will be able to freely ask questions about the hackathon through a dedicated discord channel as well as engage with other participants.
* The Everyday AI Hackathon is an open science event: all tutorials and examples are developed openly and will be publicly available during and following the hackathon. Participants will strengthen their practice of open science, using open source code and “hacking” their projects openly to enable further discovery and contributions by the broader open community following the hackathon.
* Throughout the hackathon, participants will learn about Hugging Face's impact on AI workflows for model and dataset discovery, usage, and prototyping to enable faster, more efficient time to science.

In the two weeks leading up to the hackathon, participants are encouraged to review **background resources** that will faciliate a more effective hackathon experience. These resources will be shared here leading up to the Hackathon dates, and will be accessible to all data users, whether they attend the hackathon or not.

**The following datasets are currently available from the Hugging Face Hub.** Participants can choose to prototype a cloud-based science workflow using a combination of these datasets, as well as data from other sources (e.g. AI Hub). If your preferred dataset is not yet available in the Hugging Face Hub, consider using a current cloud-based dataset as proxy to explore prototyping.

**Example use cases** to explore (note these are for inspiration only, you are not limited to these workflows):


* TODO

This event is motivated by the dawn of the era of AI. Hugging Face is in the process of collecting models and datasets to its Hub, driven by a rapid rate of transformers-based innovations in the industry. More will be available in the Hugging Face Hub in the coming years. The paradigm shift from on-premise (local) to cloud-based model distribution, and that from “build from scratch” to “use and iterate” present opportunities and challenges. Guiding users through this transition is of the utmost importance.

## FAQ

- **Q: Who can apply to participate in the hackathon?**

  A: Anyone with an interest in AI and Hugging Face technology, from beginners to advanced users, is welcome to apply.

- **Q: Is there any fee to attend the hackathon?**

  A: No, the event is free to attend, but an application is required.

- **Q: Will there be any prizes or certificates for participants?**

  A: Yes, prizes will include certificates, official Hugging Face swags, and Hugging Face Hub credits.

- **Q: Can I participate if I don’t have any experience with Hugging Face technology?**

  A: Absolutely! The hackathon is a learning experience, and participants of all levels are encouraged to apply.

- **Q: Will there be any post-event engagement or follow-up?**

  A: Yes, efforts will be made to sustain engagement and collaboration within the community post-event, with platforms or forums for continued knowledge sharing and interaction.

## Code of Conduct

The 2023 Everyday AI Hackathon is a safe learning space and all participants are required to abide by our [Code of Conduct](https://pseudo-lab.github.io/code-of-conduct).

## Acknowledgements

The Everyday AI Hackathon: A Hugging Face Community Event is hosted by PseudoLab and sponsored by Hugging Face, aiming to foster innovation and learning within the Korean AI community.

We thank all of the additional PseudoLab members that have have joined as helpers.

Thank you to the open science community that has created software, teaching resources, and workflows that we have been able to build heavily from! These include:

- NASA, eScience Institute, University of Washington:
  - <https://nasa-openscapes.github.io/2021-Cloud-Hackathon/>
  - <https://uwhackweek.github.io/hackweeks-as-a-service/intro.html>
  - <https://snowex-hackweek.github.io/website/intro.html>
  - <https://icesat-2hackweek.github.io/learning-resources/>

This hackathon book is made with [quarto](https://quarto.org). See the [earthdata-cloud-cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/) to learn more about how we work and contributing.
